### ISSUE TITLE
browser.DEFAULT_CMD undefined

### ISSUE THREAD

**Issue by kumavis** [litixsoft/karma-detect-browsers#19] opened 2016-11-09 21:42 UTC
```
09 11 2016 16:39:09.664:INFO [preprocessor.env]: Publishing variables:  []
/home/user/dev/ethereumjs-tx/node_modules/karma-detect-browsers/index.js:24
                browserPaths = browser.DEFAULT_CMD[process.platform] || [],
                                                  ^

TypeError: Cannot read property 'linux' of undefined
    at getInstalledBrowsers (/home/user/dev/ethereumjs-tx/node_modules/karma-detect-browsers/index.js:24:51)
    at DetectBrowsers (/home/user/dev/ethereumjs-tx/node_modules/karma-detect-browsers/index.js:64:28)
    at Array.invoke (/home/user/dev/ethereumjs-tx/node_modules/di/lib/injector.js:75:15)
    at Injector.get (/home/user/dev/ethereumjs-tx/node_modules/di/lib/injector.js:48:43)
    at /home/user/dev/ethereumjs-tx/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at Server._start (/home/user/dev/ethereumjs-tx/node_modules/karma/lib/server.js:142:21)
    at Injector.invoke (/home/user/dev/ethereumjs-tx/node_modules/di/lib/injector.js:75:15)
    at Server.start (/home/user/dev/ethereumjs-tx/node_modules/karma/lib/server.js:103:18)
    at Object.exports.run (/home/user/dev/ethereumjs-tx/node_modules/karma/lib/cli.js:280:26)
    at Object.<anonymous> (/home/user/dev/ethereumjs-tx/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by nickmccurdy** [comment] 2016-11-09 21:48
Duplicate of #17. Please close.

**Closed** 2016-11-09 21:49 UTC
